### ISSUE TITLE
To and CC boxes do not display selected recipients

### ISSUE THREAD

**Issue by mattzuba** [eNkru/freelook#15]
Screenshot to more accurately show. I'm using this on Office365.  Top portion of the screenshot show the email in Chrome, bottom shows it in this app.

![image](https://user-images.githubusercontent.com/1494713/61651072-f4326e00-ac69-11e9-9731-2fc5f4e8a99a.png)

**Comment by eNkru** [comment]
I've tested my office365 account (office.com), it looks good.

![Screenshot from 2019-07-23 09-34-51](https://user-images.githubusercontent.com/13460738/61667285-b0a13800-ad2d-11e9-93c1-bd2357a719d3.png)

which operation system are you running? if possible, could you run the development mode, see if any error in the terminal console or chrome web console? (press F12) after the app running in dev mode.

**Comment by mattzuba** [comment]
I'm currently on Deepin 15.11.  Here's what I'm seeing in the dev tools window:

![image](https://user-images.githubusercontent.com/1494713/61976753-717b1d00-afa1-11e9-809b-2dac1e5781cc.png)

I notice that when I go to create a new message, when I enter the first name, it briefly shows up and then hides (my email will still send to them, I just can't see their name in the To box), but subsequent recipients are hidden immediately after selecting them.

**Comment by mattzuba** [comment]
Another observation - it works properly on the _old_ Outlook layout, but not on the new.

**Comment by eNkru** [comment]
Electron is using the open source version of Chrome (Chromium), this might be a bug in the Chromium or Deepin.

The bug doesn't appear on my Arch Linux, I am guessing it shouldn't be a bug on the Chromium, so might because the Deepin Linux. Deepin Linux have quite deep modification on the UI and looks really awesome.

Just wondering if you have another linux distribution or try to use Gnome 3 on your Deepin Linux, see if the issue still resist. 

Another try is downgrade the Electron (currently on 5.0.4). Try to downgrade to version 4, see if the issue is gone. As you can running in dev mode, it's easy change the package.json the electron version to last stable version 4. the issue might gone :)

Sorry can't help too much. I've tried Deepin linux before, have a lot of compatible issues with the UI. I personally prefer Gnome.

**Comment by chrispittman** [comment]
For what it's worth, upgrading `electron` to "^6.0.11" and rebuilding the app fixes this for me.

**Comment by eNkru** [comment]
good to know @chrispittman, I'll upgrade the electron to 6 :)
