### ISSUE TITLE
Tray Icon not updating

### ISSUE THREAD

**Issue by Chinney** [eNkru/freelook#22]
Hi!

I'm having a little problem with Freelook on Ubuntu 16.04:

For a few months now the tray icon is not updating anymore upon receiving a new email. It just stays the default icon. I tried to debug it myself without any progress. I have pulled the latest changes on master and compiled it myself. Although I can see that there were some changes made in the tray controller the problem remains.

Any suggestions?

Cheers

**Comment by eNkru** [comment]
A event listener is added to the UI component to check if the inbox have unread message. Microsoft's latest update changed the class value on that component, so that listener isn't working anymore :)

I'll update the value when got some time to make it shine again. However, we do need to find out a way to avoid this because they will change the value in the future again. I reckon, the value is regenerated when they release a new version of webmail.

**Comment by eNkru** [comment]
@Chinney it's been fixed with [this commit](https://github.com/eNkru/freelook/commit/5be6bfa06a11e0a37aa23e73b51ff8465676c4ca).

MS update the related class in their release, the hard coded query will break when the value changed. An setting entry is provided to configure the class value. The app requires restart to take the change.

Please find the relevant class for unread message div and update your setting. The current one is `_3Jn_7Iv4SwMTMOPJiydZLa`. Don't know how long it will last :)

**Comment by Chinney** [comment]
Hey! Thanks alot! Unfortunately it seemed to have changed again. If you could tell me which UI Element exactly you're looking for I could fix it myself. I have tried quite a few but without success...

**Comment by eNkru** [comment]
my one still using `_3Jn_7Iv4SwMTMOPJiydZLa` seems good for me.

![image](https://user-images.githubusercontent.com/13460738/74110449-a2dfd100-4bf1-11ea-9704-9505dc9fb5e1.png)

**Comment by Chinney** [comment]
Strange. It's working for me now too. Thanks!

Anyways, my question was aiming at finding out which modules class you inserted here (it is a css class right?)? I tried quite a few...

**Comment by eNkru** [comment]
> Strange. It's working for me now too. Thanks!
> 
> Anyways, my question was aiming at finding out which modules class you inserted here (it is a css class right?)? I tried quite a few...

You are correct. It's the class value of the number of unread emails beside the Inbox

![image](https://user-images.githubusercontent.com/13460738/74483674-c3729880-4f1b-11ea-9068-78774f35ef59.png)

The class value of the nubmer in the two Inbox are same, so either of them will work with new email notification :)

![image](https://user-images.githubusercontent.com/13460738/74483785-0af92480-4f1c-11ea-9b4e-ba363b9015a3.png)

That's the class you are looking for. Note, the value is the outer span's class, not the inner one

**Comment by Chinney** [comment]
Alrite, prefect, thank You!
